CREATE TABLE USERS
(
    ID          SERIAL PRIMARY KEY,
    FIRSTNAME   VARCHAR(100),
    LASTNAME    VARCHAR(100)
);

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("John", "Smith");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("Zachary", "Lee");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("Stephanie", "Kovalsky");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("Thomas", "Landgren");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("John", "Thomson");

COMMIT;

SELECT * FROM USERS;


CREATE TABLE POSTS
(
    ID          SERIAL PRIMARY KEY,
    USER_ID     BIGINT UNSIGNED NOT NULL,
    BODY        VARCHAR(1024),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "This is my first post on this forum!");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "This is my first post too!");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "How are you?");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "Quite good, thanks bro!");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (4, "Yo all! Here is Thomas!");

COMMIT;
SELECT * FROM POSTS;



CREATE TABLE ISSUESLISTS
(
ID SERIAL PRIMARY KEY,
NAME CHAR
);

INSERT INTO ISSUESLISTS (NAME)
VALUES ("ToDo");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("In progres");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("Done");

COMMIT;

CREATE TABLE ISSUES
(
ID serial primary KEY,
ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
SUMMARY CHAR,
DESCRIPTION VARCHAR(1500),
USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)
);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Facebook post", "Write Facebook post inviting to the concert", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Contact with the media", "Invitation for the media", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "TV interview arr.", "Arranging an interview on TV", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Lighting", "Ordering lighting for the concert hall", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Speach", "Preparation of the speech", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "POSTER", "Designing poster and other advertising materials", 5);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "REHEARSALS", "Rehearsals of orchestra and choirs", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "HOTEL", "Accommodation of musicians in the hotel", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Media patronage", "Sending requests for media patronage", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Translator", "Translator for the conductor", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "PROJECT", "Writing a project", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "MONEY", "Negotiations with sponsors", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "MONEY", "Negotiations with sponsors", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Artists", "Netotiations with artists", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "PROGRAM", "Writing a program of concert", 1);

COMMIT;

SELECT * FROM ISSUES;